//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Lib.rc
//
#define AboutBox                        101
#define ID_DIG_LOGIN                    101
#define ABOUT1                          102
#define ID_CLIENT_MENU                  102
#define ID_DLG_CLIENT                   104
#define IDR_TOOLBAR1                    105
#define IDR_TOOLBAR                     122
#define IDI_ICON1                       126
#define IDI_ICON2                       127
#define IDI_ICON3                       128
#define IDI_ICON4                       129
#define IDI_ICON5                       130
#define ID_DLG_OPERATOR_M               132
#define ID_DLG_BOOK_INFO                133
#define IDB_BITMAP_CLIENT               135
#define ID_DLG_INPUT_QUERY              138
#define ID_DLG_CONFIG                   139
#define IDC_EDIT_NAME                   1000
#define IDC_EDIT_PASSWORD               1001
#define IDC_BTN_LOGIN                   1002
#define IDC_BTN_CANCEL                  1003
#define IDC_EDIT_PWD                    1004
#define IDC_COMBO_LEVEL                 1006
#define IDC_LIST_VIEW                   1010
#define IDC_COMBO_KINDS                 1018
#define IDC_PROVIDER                    1024
#define IDC_PROVIDER_CEO                1025
#define IDC_COMBO_STORE                 1025
#define IDC_MANAGER                     1026
#define IDC_PROVIDER_PHONE              1027
#define IDC_PROVIDER_ADDRESS            1028
#define IDC_PROVIDER_NETADDRESS         1029
#define IDC_PROVIDER_EMAIL              1030
#define IDC_BOOK_KINDS                  1031
#define IDC_EDIT_STORE                  1032
#define IDC_EDIT_DESK                   1033
#define IDC_BUTTON_SUB                  1033
#define IDC_OPERATOR                    1035
#define IDC_COMBO_DESK                  1035
#define IDC_ADJUST_OPERATOR             1035
#define IDC_SUMMONEY                    1036
#define IDC_REBATE                      1037
#define IDC_INPUT_REBATE                1037
#define IDC_PAYMONEY                    1038
#define IDC_FACTMONEY                   1039
#define IDC_SELLPRICE                   1041
#define IDC_EDIT_ADJUSTPRICE            1042
#define IDC_CUSTOMER                    1043
#define IDC_STORELIST                   1043
#define IDC_BACK_BARCODE                1044
#define IDC_ADJUST_PROVIDER             1044
#define IDC_BOOK_CONDITIONLIST          1044
#define IDC_BACK_NUM                    1045
#define IDC_ADJUST_BARCODE              1045
#define IDC_BACK_BOOKREBATE             1046
#define IDC_ADJUST_COUNT                1046
#define IDC_BACK_SELLPRICE              1047
#define IDC_STARTTIME                   1047
#define IDC_BACK_BOOKNAME               1048
#define IDC_EDIT_IP                     1048
#define IDC_BACK_AUTHOR                 1049
#define IDC_EDIT_USER                   1049
#define IDC_BACK_SUMMONEY               1050
#define IDC_BUTTON_CONFIG               1050
#define IDC_BACK_REBATE                 1051
#define IDC_EDIT_DBASE                  1051
#define IDC_BACK_PAYMONEY               1052
#define IDC_BOOK_PROPERTY               1052
#define IDC_BACK_FACTMONEY              1053
#define IDC_BUTTON_CANCEL               1053
#define IDC_STORE_CHECK                 1053
#define IDC_SALE_CUSTOMER               1054
#define IDC_BOOK_CHECK                  1054
#define IDC_SALE_BARCODE                1055
#define IDC_SALE_NUM                    1056
#define IDC_SALE_COUNT                  1056
#define IDC_SALE_BOOKREBATE             1057
#define IDC_SALE_CONCERN                1057
#define IDC_SALE_SELLPRICE              1058
#define IDC_SALE_BOOKNAME               1059
#define IDC_SALE_AUTHOR                 1060
#define IDC_SALE_SUMMONEY               1061
#define IDC_SALE_REBATE                 1062
#define IDC_SALE_PAYMONEY               1063
#define IDC_SALE_FACTMONEY              1064
#define IDC_IB_PROVIDER                 1065
#define IDC_IB_SUMMONEY                 1066
#define IDC_IB_REBATE                   1067
#define IDC_IB_PAYMONEY                 1068
#define IDC_IB_FACTMONEY                1069
#define IDC_IQ_VALUE                    1070
#define IDC_IBQ_EDIT_VALUE              1071
#define IDC_SQ_EDIT_VALUE               1072
#define IDC_SQ_VALUE                    1072
#define IDC_SBQ_EDIT_VALUE              1073
#define IDC_NEDIT_BARCODE               1540
#define IDC_DISEDIT_OPERATOR            1541
#define ID_DLG_PROVIDER_INFO            2134
#define ID_DLG_BOOK_KINDS               2135
#define ID_DLG_STORE_INFO               2136
#define ID_DLG_DESK_INFO                2137
#define ID_DLG_BOOK_INPUT               2138
#define ID_DLG_BOOK_PRICE               2139
#define ID_DLG_BOOK_ADJUST_PRICE        2140
#define ID_DLG_SALE_BACK                2141
#define ID_DLG_BOOK_ADJUST              2142
#define ID_DLG_BOOK_SALE                2143
#define ID_DLG_INPUT_BACK               2144
#define ID_DLG_INPUT_BACK_QUERY         2145
#define ID_DLG_SALE_QUERY               2146
#define ID_DLG_QUERY                    2146
#define ID_DLG_SALE_BACK_QUERY          2147
#define ID_DLG_STOCKQUERY               2148
#define IDC_INPUT_OPERATOR              2150
#define IDC_INPUT_PROVIDER              2151
#define IDC_INPUT_BOOKNAME              2152
#define IDC_INPUT_BARCODE               2152
#define IDC_INPUT_COUNT                 2153
#define IDC_STORAGELIST                 3001
#define IDC_TAKELIST                    3001
#define IDC_PROVIDERLIST                3002
#define IDC_FIELDSLIST                  3003
#define IDC_CONDITIONLIST               3003
#define IDC_VALUELIST                   3004
#define IDC_COMBO_COUNTERNAME           3005
#define IDC_COUNTERLIST                 3006
#define IDC_EDIT_BARCODE                3300
#define IDC_EDIT_BOOKNAME               3301
#define IDC_EDIT_MNCODE                 3302
#define IDC_EDIT_AUTHOR                 3303
#define IDC_EDIT_PUBLIC                 3304
#define IDC_EDIT_PRICE                  3305
#define IDC_EDIT_MEMO                   3306
#define IDC_SUB_VIEW                    4001
#define IDC_DATETIME                    5001
#define IDC_DATETIME2                   5002
#define IDC_ENDTIME                     5002
#define IDC_CHECK_SELECT                6001
#define IDC_SELECT_CHECK                6001
#define IDC_CHECK_TIME                  6002
#define IDC_TIME_CHECK                  6002
#define IDC_CANCEL                      11019
#define IDC_CLEAR                       11019
#define IDC_BUTTON_ADD                  11020
#define IDC_BUTTON_MODIFY               11021
#define IDC_BUTTON_DELETE               11022
#define IDC_QUERY                       11022
#define ID_QUIT                         11023
#define IDC_PRINT                       11024
#define IDM_APP_ABOUT                   40001
#define ID_EXIT                         40001
#define ID_BUTTON40002                  40002
#define ID_TB_CONFIG                    40003
#define ID_TB_EXIT                      40004
#define ID_1                            40011
#define ID_OPERATOR_M                   40012
#define ID_BOOK_INFO                    40013
#define ID_PROVIDER_INFO                40014
#define ID_CK_INFO                      40015
#define ID_DESK_INFO                    40016
#define ID_BOOK_INPUT                   40017
#define ID_BOOK_PRICE                   40018
#define ID_BOOK_PRICE_ADJUST            40019
#define ID_INPUT_BACK                   40020
#define ID_BOOK_ADJUST                  40021
#define ID_SALE_M                       40022
#define ID_SALE_BACK                    40023
#define ID_INPUT_QUERY                  40024
#define ID_INPUT_BACK_QUERY             40025
#define ID_SALE_QUERY                   40026
#define ID_SALE_BACK_QUERY              40027
#define IDD_ABOUTBOX                    40028
#define IDD_PROVIDER_INFO1              40029
#define ID_BOOK_KIND                    40029
#define ID_STOCK_QUERY                  40030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
